package demos;

import iaik.asn1.structures.GeneralName;
import iaik.x509.X509Certificate;

import java.security.cert.CertificateException;
import java.security.cert.CertificateParsingException;
import java.util.Iterator;
import java.util.List;


public class SubjectAltNameDemo {
    
    // demo cert generated by https://8gwifi.org/SelfSignCertificateFunctions.jsp
    private static String demoCert1 = "-----BEGIN CERTIFICATE-----\n" +
            "MIID+zCCAuOgAwIBAgIhAKrSVvdqxNIJ79FTRhd+OoOoLc0ETZHY1VNN2hTIT/oZ\n" +
            "MA0GCSqGSIb3DQEBBQUAMIGKMQ0wCwYDVQQGEwRHcmF6MQwwCgYDVQQKDANUVUcx\n" +
            "DTALBgNVBAsMBElBSUsxHTAbBgNVBAMMFHNtb3JlLmlhaWsudHVncmF6LmF0MR4w\n" +
            "HAYJKoZIhvcNAQkBFg9zbW9yZUB0dWdyYXouYXQxHTAbBgNVBAMMFHNtb3JlLmlh\n" +
            "aWsudHVncmF6LmF0MB4XDTE5MDMwNjEzMzgwNFoXDTI5MDMwNjEzMzgwNFowazEN\n" +
            "MAsGA1UEBhMER3JhejEMMAoGA1UECgwDVFVHMQ0wCwYDVQQLDARJQUlLMR0wGwYD\n" +
            "VQQDDBRzbW9yZS5pYWlrLnR1Z3Jhei5hdDEeMBwGCSqGSIb3DQEJARYPc21vcmVA\n" +
            "dHVncmF6LmF0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0EBASkXD\n" +
            "83c6HwNhNVi62FHVrau/sboEHARc6N4uBSbYZ1G/DgCgs64+EHo9wE9wCdT7KoU5\n" +
            "WPe81zbONU7sH8BoN/iVJHz/sQiyAnrf1YiDDLBQtK4AHeBsLYrKGGqaPEvRQ3+D\n" +
            "YvmGox7k0wHAK/Vlyzlx6ng7nOIvFcSGUSfo/z4JraPFcAwYYtRW8Nof9Jg4WQP4\n" +
            "BmPAep5tpJt8lINWAy/tfuCKGJzohODU2rR66Ge8awIXPZMm2/Gk8FY2Z36iOWde\n" +
            "vkv1xoyg5sMnVfzFOTcZCKcyYrwOF8/AlnhDDEM7eaI0JKjQEooSW8AbfMtFNCHN\n" +
            "WZaFcLdHPo0wSQIDAQABo2owaDAdBgNVHQ4EFgQUb8i1O4/JjQhPhl/UHwNgP3Uo\n" +
            "bfswHwYDVR0jBBgwFoAUb8i1O4/JjQhPhl/UHwNgP3UobfswJgYDVR0RBB8wHYIb\n" +
            "ZGVtbzEubGlnaHRlc3QubmxuZXRsYWJzLmV1MA0GCSqGSIb3DQEBBQUAA4IBAQCu\n" +
            "IuOxOIoMSjy1FWigNGYDakrX6g0Ht7c02IR6ZypKoIWrF6JISXUZJXjo+m8vFq7F\n" +
            "RMHpvFSrGZ60t90i78zvRMSVlmlTASERcSRwXAuMmBN5pXsHcs5UHwzrwF6iv4xH\n" +
            "oe60T80z5EAlza/6w63YSNiamsA5NkeGeKdebaGjhVo/fLvVJG2pzMR48cJWRzwy\n" +
            "GR1gzLnpxG0s2EEIjcJPGmZ37j6gCaNtDXfIf0SaH08aJ7fze7Utet0mb2ltLzZK\n" +
            "kgC6s65XcQWYHgwT8QeUFVDFZ3vnrnDAxRIVqMNFNzDK0YUMfQWD+uhNdpbTXJsn\n" +
            "h79j1Q7/DVSOl3yz/byO\n" +
            "-----END CERTIFICATE-----\n";
    
    public static void main(String[] args) throws CertificateException {
        
        X509Certificate cert = new X509Certificate(SubjectAltNameDemo.demoCert1.getBytes());
        SubjectAltNameDemo.getSubjectAltNames(cert);
    }
    
    protected static void getSubjectAltNames(X509Certificate cert) throws CertificateParsingException {
        
        //System.out.println("Parsing certificate " + cert.toString());
        
        if(cert.getSubjectAlternativeNames() != null) {
            Iterator it = cert.getSubjectAlternativeNames().iterator();
            while(it.hasNext()) {
                // look for URI
                List list = (List) it.next();
                
                Integer type = (Integer) list.get(0);
                String name = SubjectAltNameDemo.getNameOfType(type);
                String value = (String) list.get(1);
                System.out.println("type: " + type + " (" + name + "), value: " + value);
            }
        }
    }
    
    private static String getNameOfType(int type) {
        
        switch(type) {
            case GeneralName.dNSName:
                return "dNSName";
            default:
                // see for other names: http://javadoc.iaik.tugraz.at/iaik_jce/current/iaik/asn1/structures/GeneralName.html#field_detail
                return "invalid type";
        }
    }
}
